brew "awscli"
brew "jq"
brew "mise"

cask "1password"
cask "caffeine"
cask "dash"
cask "docker-desktop"
cask "flycut"
cask "hex-fiend"
cask "iterm2"
cask "runjs"
cask "visual-studio-code"

# Recursive Mono font
cask "font-recursive-code"
