#!/usr/bin/env sh

set -eu

cd "$(dirname $0)"/..

# Ordered so dependencies are resolved
packages="
homebrew
iterm2
nova
bash
zsh
git
"
echo "$packages" | while read package; do
  if [ -f "$package/install.sh" ]; then
    echo "🔵 Installing $package..."
    sh -c "$package/install.sh"
  fi
done
