#!/usr/bin/env sh

set -u

cd "$(dirname $0)"/..

# Ordered so dependencies are resolved
packages="
homebrew
git
iterm2
nova
bash
zsh
env
"
echo "$packages" | while read package; do
  if [ -f "$package/install.sh" ]; then
    echo "🔵 Installing $package..."
    sh -c "$package/install.sh" || echo "❌ $package failed!"
  fi
done
